[project]
name = "db-scenario"
version = "0.1.0"
description = "DB Scenario Pro"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.128.1",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.40.0",
]

